function accountMenu(){return $('#account-menu')}
function closeAccountMenu(){accountMenu()?.classList.add('hidden');$('#account-menu-button')?.setAttribute('aria-expanded','false')}
function applyTheme(){document.documentElement.dataset.theme='light';localStorage.removeItem('shiftrelay-theme')}
function openPreferences(){closeAccountMenu();const existing=$('#preferences-dialog');if(existing){existing.remove();return}document.body.insertAdjacentHTML('beforeend',`<section class="profile-dialog" id="preferences-dialog"><div><button class="dialog-close" aria-label="Close">×</button><p class="eyebrow">PERSONAL PREFERENCES</p><h2>Make ShiftRelay feel right.</h2><p>Choose the display language that is easiest for your shift.</p><label class="language-choice"><span>Display language</span><select id="language-select">${Object.entries(languages).map(([code,name])=>`<option value="${code}" ${appLanguage()===code?'selected':''}>${name}</option>`).join('')}</select></label></div></section>`);$('.dialog-close').addEventListener('click',()=>$('#preferences-dialog').remove());$('#language-select').addEventListener('change',(event)=>setAppLanguage(event.target.value))}
function openPasswordChange(){closeAccountMenu();const existing=$('#password-dialog');if(existing){existing.remove();return}document.body.insertAdjacentHTML('beforeend',`<section class="profile-dialog" id="password-dialog"><div><button class="dialog-close" aria-label="Close">×</button><p class="eyebrow">ACCOUNT SECURITY</p><h2>Change password</h2><form class="access-form" id="password-form"><label>Current password<input name="currentPassword" type="password" required autocomplete="current-password" /></label><label>New password<input name="newPassword" type="password" minlength="10" required autocomplete="new-password" /></label><label>Confirm new password<input name="confirmPassword" type="password" minlength="10" required autocomplete="new-password" /></label><p class="form-message" id="password-message"></p><button class="primary" type="submit">Update password</button></form></div></section>`);$('.dialog-close').addEventListener('click',()=>$('#password-dialog').remove());$('#password-form').addEventListener('submit',async(event)=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));if(form.newPassword!==form.confirmPassword){$('#password-message').textContent='New passwords do not match.';return}try{await api('/api/auth/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});$('#password-dialog').remove();toast('Password updated successfully.')}catch(error){$('#password-message').textContent=error.message}})}
function signOut(){closeAccountMenu();$('#logout-button').click()}
function renderAccountMenu(){if(accountMenu())return;document.body.insertAdjacentHTML('beforeend',`<aside class="account-menu hidden" id="account-menu"><button class="account-profile" data-account-action="profile"><span class="avatar" id="account-avatar"></span><span><strong>${escape(state.user?.name||'My profile')}</strong><small>Edit profile photo and details</small></span></button><div class="account-menu-list"><button data-account-action="preferences">Preferences</button><button data-account-action="password">Change password</button>${state.user?.role==='owner'?'<button data-account-action="settings">Organisation settings</button>':''}<button data-account-action="delete-account">Delete account</button><button data-account-action="signout" class="danger">Sign out</button></div><footer>© ${new Date().getFullYear()} ShiftRelay</footer></aside>`);const avatar=$('#account-avatar');if(state.user?.avatar_data_url)avatar.innerHTML=`<img src="${state.user.avatar_data_url}" alt="" />`;else avatar.textContent=(state.user?.name||'?').split(' ').map((part)=>part[0]).join('');accountMenu().addEventListener('click',(event)=>{const action=event.target.closest('[data-account-action]')?.dataset.accountAction;if(action==='profile'){closeAccountMenu();openProfile()}if(action==='preferences')openPreferences();if(action==='password')openPasswordChange();if(action==='settings'){closeAccountMenu();go('settings')}if(action==='delete-account')window.location.assign('/delete-account.html');if(action==='signout')signOut()})}
document.addEventListener('click',(event)=>{if(event.target.closest('#account-menu-button')){renderAccountMenu();const menu=accountMenu();menu.classList.toggle('hidden');$('#account-menu-button').setAttribute('aria-expanded',String(!menu.classList.contains('hidden')))}else if(!event.target.closest('#account-menu'))closeAccountMenu()});
applyTheme();
