const languages={en:'English',fr:'Français',es:'Español',sw:'Kiswahili',ar:'العربية'};
const translations={fr:{Dashboard:'Tableau de bord',Notifications:'Notifications',Calendar:'Calendrier',Staffs:'Personnel',Workflows:'Flux de travail',Analytics:'Analyses',Incidents:'Incidents',Settings:'Paramètres',Preferences:'Préférences','Change password':'Modifier le mot de passe','Sign out':'Se déconnecter',Review:'À examiner','Incoming shift':'Équipe entrante',Acknowledged:'Confirmé','New handover':'Nouvelle relève',Activity:'Activité','Good morning':'Bonjour','Good afternoon':'Bon après-midi','Good evening':'Bonsoir'},es:{Dashboard:'Panel',Notifications:'Notificaciones',Calendar:'Calendario',Staffs:'Personal',Workflows:'Flujos de trabajo',Analytics:'Análisis',Incidents:'Incidentes',Settings:'Configuración',Preferences:'Preferencias','Change password':'Cambiar contraseña','Sign out':'Cerrar sesión',Review:'Revisión','Incoming shift':'Turno entrante',Acknowledged:'Confirmado','New handover':'Nueva entrega',Activity:'Actividad','Good morning':'Buenos días','Good afternoon':'Buenas tardes','Good evening':'Buenas noches'},sw:{Dashboard:'Dashibodi',Notifications:'Arifa',Calendar:'Kalenda',Staffs:'Wafanyakazi',Workflows:'Mtiririko wa kazi',Analytics:'Takwimu',Incidents:'Matukio',Settings:'Mipangilio',Preferences:'Mapendeleo','Change password':'Badilisha nenosiri','Sign out':'Ondoka',Review:'Mapitio','Incoming shift':'Zamu inayofuata',Acknowledged:'Imethibitishwa','New handover':'Makabidhiano mapya',Activity:'Shughuli','Good morning':'Habari za asubuhi','Good afternoon':'Habari za mchana','Good evening':'Habari za jioni'},ar:{Dashboard:'لوحة التحكم',Notifications:'الإشعارات',Calendar:'التقويم',Staffs:'الموظفون',Workflows:'مسارات العمل',Analytics:'التحليلات',Incidents:'الحوادث',Settings:'الإعدادات',Preferences:'التفضيلات','Change password':'تغيير كلمة المرور','Sign out':'تسجيل الخروج',Review:'للمراجعة','Incoming shift':'الوردية القادمة',Acknowledged:'تم التأكيد','New handover':'تسليم جديد',Activity:'النشاط','Good morning':'صباح الخير','Good afternoon':'مساء الخير','Good evening':'مساء الخير'}};
const languageOriginals=new WeakMap();
function appLanguage(){return localStorage.getItem('shiftrelay-language')||'en'}
function formatLocale(){return appLanguage()==='sw'?'sw-KE':appLanguage()==='ar'?'ar':appLanguage()}
function translateInterface(root=document.body){const dictionary=translations[appLanguage()]||{};root.querySelectorAll('*').forEach((element)=>{if(element.children.length)return;for(const node of element.childNodes){if(node.nodeType!==Node.TEXT_NODE||!node.nodeValue.trim())continue;const source=languageOriginals.get(node)||node.nodeValue.trim();languageOriginals.set(node,source);if(dictionary[source])node.nodeValue=node.nodeValue.replace(source,dictionary[source])}});document.documentElement.lang=appLanguage();document.documentElement.dir=appLanguage()==='ar'?'rtl':'ltr'}
function setAppLanguage(language){localStorage.setItem('shiftrelay-language',language);translateInterface();document.dispatchEvent(new Event('shiftrelay-language-change'))}
new MutationObserver(()=>translateInterface()).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('DOMContentLoaded',()=>translateInterface());
